export const styles = {
  app: {
    fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
    backgroundColor: "#f1f5f9",
    minHeight: "100vh",
    color: "#1a202c",
  },
  navbar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#0f172a",
    padding: "14px 30px",
    color: "#fff",
    flexWrap: "wrap",
    gap: "10px",
  },
  logo: { fontSize: "18px", fontWeight: 700, letterSpacing: "0.3px" },
  navRight: { display: "flex", alignItems: "center", gap: "12px", flexWrap: "wrap" },
  roleBadge: {
    backgroundColor: "#1e293b",
    color: "#93c5fd",
    padding: "3px 10px",
    borderRadius: "999px",
    fontSize: "11px",
    fontWeight: 700,
    border: "1px solid #334155",
  },
  connectBtn: {
    backgroundColor: "#3b82f6",
    color: "white",
    border: "none",
    padding: "9px 16px",
    borderRadius: "8px",
    fontWeight: 600,
    cursor: "pointer",
  },
  connectedBtn: {
    backgroundColor: "#16a34a",
    color: "white",
    border: "none",
    padding: "9px 16px",
    borderRadius: "8px",
    fontWeight: 600,
    cursor: "default",
  },
  body: { padding: "26px", maxWidth: "1200px", margin: "0 auto" },
  banner: {
    backgroundColor: "#fff",
    borderLeft: "5px solid #3b82f6",
    padding: "12px 18px",
    borderRadius: "6px",
    boxShadow: "0 1px 3px rgba(0,0,0,0.06)",
    marginBottom: "22px",
  },
  log: {
    backgroundColor: "#0f172a",
    color: "#7dd3fc",
    padding: "10px 12px",
    borderRadius: "6px",
    fontSize: "12px",
    fontFamily: "monospace",
    marginTop: "10px",
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  },
  statRow: { display: "flex", gap: "16px", flexWrap: "wrap", marginBottom: "24px" },
  statCard: {
    flex: "1 1 160px",
    backgroundColor: "#fff",
    padding: "18px 20px",
    borderRadius: "10px",
    boxShadow: "0 1px 3px rgba(0,0,0,0.06)",
    border: "1px solid #e2e8f0",
  },
  statNum: { fontSize: "28px", fontWeight: 800, color: "#0f172a" },
  statLabel: { fontSize: "12px", color: "#64748b", marginTop: "2px", textTransform: "uppercase", letterSpacing: "0.5px" },
  grid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(340px, 1fr))", gap: "22px", marginBottom: "26px" },
  card: {
    backgroundColor: "#fff",
    padding: "22px",
    borderRadius: "10px",
    boxShadow: "0 1px 3px rgba(0,0,0,0.06)",
    border: "1px solid #e2e8f0",
  },
  cardTitle: { margin: "0 0 4px 0", fontSize: "16px", color: "#0f172a", fontWeight: 700 },
  cardSub: { margin: "0 0 16px 0", fontSize: "12px", color: "#64748b" },
  formGroup: { display: "flex", flexDirection: "column", marginBottom: "12px" },
  label: { fontSize: "11px", fontWeight: 700, color: "#475569", marginBottom: "4px", textTransform: "uppercase" },
  input: {
    padding: "10px",
    borderRadius: "8px",
    border: "1px solid #cbd5e1",
    fontSize: "13px",
    outline: "none",
    backgroundColor: "#f8fafc",
  },
  btn: {
    color: "white",
    border: "none",
    padding: "10px 14px",
    borderRadius: "8px",
    fontSize: "13px",
    fontWeight: 600,
    cursor: "pointer",
    backgroundColor: "#3b82f6",
  },
  btnGreen: { backgroundColor: "#16a34a" },
  btnAmber: { backgroundColor: "#d97706" },
  btnRed: { backgroundColor: "#dc2626" },
  btnGray: { backgroundColor: "#475569" },
  btnSm: { padding: "6px 10px", fontSize: "12px" },
  btnDisabled: { opacity: 0.5, cursor: "not-allowed" },
  sectionTitle: {
    fontSize: "17px",
    margin: "8px 0 16px 0",
    color: "#0f172a",
    borderBottom: "2px solid #cbd5e1",
    paddingBottom: "8px",
  },
  table: { width: "100%", borderCollapse: "collapse", fontSize: "13px", textAlign: "left" },
  th: { borderBottom: "2px solid #e2e8f0", color: "#475569", backgroundColor: "#f8fafc", padding: "8px 6px" },
  td: { borderBottom: "1px solid #eef2f7", padding: "8px 6px", verticalAlign: "middle" },
  emptyTd: { padding: "22px", textAlign: "center", color: "#94a3b8", fontStyle: "italic" },
  badge: (b) => ({
    backgroundColor: b.bg,
    color: b.fg,
    padding: "2px 8px",
    borderRadius: "6px",
    fontSize: "11px",
    fontWeight: 700,
    whiteSpace: "nowrap",
  }),
  pill: {
    display: "inline-block",
    backgroundColor: "#e2e8f0",
    color: "#334155",
    padding: "2px 8px",
    borderRadius: "6px",
    fontSize: "11px",
    fontWeight: 600,
  },
  modalBackdrop: {
    position: "fixed",
    inset: 0,
    backgroundColor: "rgba(15,23,42,0.6)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 50,
    padding: "16px",
  },
  modal: {
    backgroundColor: "#fff",
    borderRadius: "12px",
    padding: "22px",
    width: "100%",
    maxWidth: "440px",
    boxShadow: "0 20px 40px rgba(0,0,0,0.3)",
  },
  qrBox: { display: "flex", flexDirection: "column", alignItems: "center", gap: "8px" },
};
